#      _   _           _     _____  _             _                #
#     | \ | |         | |   |  __ \| |           (_)               #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___      #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|     #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \     #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/     #
#                                           __/ |                  #
#                                          |___/                   #
#                       Servidor de Suporte                        #
#                https://nextplugins.com.br/discord                #

plugin:
  features:
    # bStats é usado apenas para os desenvolvedores terem uma noção de quantas pessoas utilizam o plugin
    useBStats: true
  # permissão que irá diferenciar players comuns de membros da staff
  permission: 'nextplugins.commandpassword.staff'
  # senha global, que será usada no lugar das senhas que não tiverem o campo 'password'
  global-password: 'nextplugins'
  # lista de comandos que terão senha
  locked-commands:
    # id, serve apenas para diferenciar os comandos
    command1:
      # comando, coloque aqui o comando que será bloqueado
      command: '/worldedit'
      # senha, aqui a senha que será requisitada para o comando ser executado
    command2:
      command: '/mercado'
    command3:
      command: '/gamemode'
      password: '321'
