#      _   _           _     _____  _             _                #
#     | \ | |         | |   |  __ \| |           (_)               #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___      #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|     #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \     #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/     #
#                                           __/ |                  #
#                                          |___/                   #
#                       Servidor de Suporte                        #
#                      discord.gg/JtTN7E6A2q                       #

plugin:
  # permissão que irá diferenciar players comuns de membros da staff
  permission: ''
  # senha global, que será usada no lugas das senhas que estiverem "null"
  global-password: 'nextplugins'
  # lista de comandos que terão senha
  locked-commands:
    # id, serve apenas para diferenciar os comandos
    command1:
      # comando, coloque aqui o comando que será bloqueado
      command: '/worldedit'
      # senha, aqui a senha que será requisitada para o comando ser executado
      password: 'null'
    command2:
      command: '/mercado'
      password: '123'
    command3:
      command: '/gamemode'
      password: '321'
